# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@8.5.2

jobs:
  test:
    docker:
      - image: 'cimg/node:8.5.2'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install 
          cache-path: ~/project/node_modules 
      - run:
          name: "React Tests"
          command: npm run test
      
      - store_test_results:
          path: Results

workflows:
  Test:
    jobs:
      - build-and-test
